version: 0.0
os: linux
files:
  - source: target/hello-jsp.war
    destination: /usr/share/tomcat/webapps
hooks:
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 180
      runas: root
