version: 0.2

phases:
  install:
    commands:
      - echo Installing Maven...
      - yum install -y maven
  build:
    commands:
      - mvn clean package
artifacts:
  files:
    - target/hello-jsp.war
    - appspec.yml
    - scripts/*
